version: '3.5'
services:
  mysql-standalone:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=swplanets
      - MYSQL_USER=durynek
      - MYSQL_PASSWORD=password
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 2s
      retries: 10
  backend:
    depends_on:
      - "mysql-standalone"
    restart: on-failure
    build:
        context: .
    ports:
      - 8989:8080
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=durynek
      - DATABASE_NAME=swplanets
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
